### ISSUE TITLE
has no attribute 'allreduce_nccl'

### ISSUE THREAD

**Issue by ewrfcas** [openai/blocksparse#24]
when i run the enwik8.py example in multi-gpus, it causes the error "has no attribute 'allreduce_nccl'" in blockspare.nccl.allreduce.

**Comment by ewrfcas** [comment]
I also run the nccl_test.py and get the same error:
<img width="1626" alt="WX20190503-211008@2x" src="https://user-images.githubusercontent.com/12042259/57139732-9c156980-6de8-11e9-8b47-133a915eb0a7.png">

**Comment by scott-gray** [comment]
I didn't compile the nccl and mpi libs into the pip package, and it's currently commented out of the Makefile.  It should be easy to comment it back in and build from source.  Though it's on my list of things to do to setup the Makefile to have multiple build targets.  I just don't have to write Makefiles frequently enough to remember the syntax.

**Comment by ewrfcas** [comment]
> I didn't compile the nccl and mpi libs into the pip package, and it's currently commented out of the Makefile. It should be easy to comment it back in and build from source. Though it's on my list of things to do to setup the Makefile to have multiple build targets. I just don't have to write Makefiles frequently enough to remember the syntax.

Thanks a lot for your advice. I have remake the blockspare_ops.so and another error is caused during 'mpirun -n 4 python nccl_test.py'
<img width="1555" alt="WX20190504-110348@2x" src="https://user-images.githubusercontent.com/12042259/57173100-affab300-6e5c-11e9-89bd-66ae8b13fe7f.png">
I think the mpi and nccl are already installed correctly and both test examples of them have been passed successfully. Since i'm new to MPI based multi-gpu training, can you give me some advices about it? Thanks.

**Comment by ewrfcas** [comment]
Finally, I solved this problem through using horovod instead of mpi4py...
